#Service and Deployment with nanomicroservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exercise
  namespace: devops-exercise
  labels:
    app: v2-exercise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v2-exercise
  template:
    metadata:
      labels:
        app: v2-exercise
    spec:
      containers:
      - name: exercise
        image: r2d2r2d2/exercise:latest
        env:
        - name: REDIS_URL
          value: "redis://v2-redis/0"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volum to /etc/nginx
          readOnly: true
          name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf

---
kind: Service 
apiVersion: v1 
metadata:
  name: v2-devops-exercise
  namespace: devops-exercise
spec:
  # For expose the service on a static port on each node
  type: NodePort
  selector:
    app: v2-exercise 
  ports:
    - nodePort: 31001
      port: 8080
      #For nginx port
      targetPort: 8080
