#Service and Deployment with nanomicroservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exercise
  namespace: devops-exercise
  labels:
    app: exercise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exercise
  template:
    metadata:
      labels:
        app: exercise
    spec:
      containers:
      - name: exercise
        image: r2d2r2d2/exercise:latest
        env:
        - name: REDIS_URL
          value: "redis://redis/0"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

---
kind: Service 
apiVersion: v1 
metadata:
  name: devops-exercise
  namespace: devops-exercise
spec:
  # For expose the service on a static port on each node
  type: NodePort
  selector:
    app: exercise 
  ports:
    - nodePort: 31000
      port: 8080 
      targetPort: 5000
