#Service and Deployment for redis and extra points 
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
#Service and Deployment with nanomicroservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exercise
  labels:
    app: exercise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exercise
  template:
    metadata:
      labels:
        app: exercise
    spec:
      containers:
      - name: exercise
        image: r2d2r2d2/exercise:0.1a
        env:
        - name: REDIS_URL
          value: "redis://redis/0"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

---
kind: Service 
apiVersion: v1 
metadata:
  name: devops-exercise 
spec:
  # For expose the service on a static port on each node
  type: NodePort
  selector:
    app: exercise 
  ports:
    - nodePort: 31000
      port: 8080 
      targetPort: 5000
