name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v2
      
    - uses: azure/docker-login@v1
      with:
        username: 'r2d2r2d2'
        password: ${{ secretspassword }}
        
    - name: Build the Docker image
      run: |
        DATE=$(date +%s)
        docker build . --file Dockerfile --tag r2d2r2d2/exercise:rc-$(DATE)
        docker push r2d2r2d2/exercise:rc-DATE
        
      
